# Generated by Django 6.0.4 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_rename_date_subject_exam_date_studyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
